package backend

import (
	"errors"
	"fmt"

	"github.com/jeffrom/job-manager/mjob/resource"
)

var ErrNotFound = errors.New("backend: not found")
var ErrBlocked = errors.New("backend: queue blocked")
var ErrInvalidState = errors.New("backend: invalid state")

// ErrInvalidResource should be returned when the resource is missing a field
// required for storage, like an ID that can't be autogenerated.
// TODO this should be a struct
var ErrInvalidResource = errors.New("backend: invalid resource")

var ErrNotAuthorized = errors.New("backend: not authorized")

type VersionConflictError struct {
	Resource   string
	ResourceID string
	Prev       string
	Curr       string
}

func NewVersionConflictError(prev, curr *resource.Version, resource, resourceID string) *VersionConflictError {
	return &VersionConflictError{
		Resource:   resource,
		ResourceID: resourceID,
	}
}

func (e *VersionConflictError) Error() string {
	return fmt.Sprintf("backend: version conflict (resource: %q prev: %q, curr: %q)", e.Resource, e.Prev, e.Curr)
}
