// Code generated by script/write_jsonschema.sh. DO NOT EDIT.
// This file was generated by script/write_jsonschema.sh.
// using data from: jsonschema/Data.json
package schema

var dataSchemaRaw = []byte(`{
    "$schema": "http://json-schema.org/schema#",
    "title": "job-manager Data schema",
    "type": "object",
    "properties": {
        "type": { "type": "string", "pattern": "^object$" },
        "properties": { "type": "object" }
    },
    "additionalProperties": false,
    "required": ["type"]
}
`)
