// Code generated by script/write_jsonschema.sh. DO NOT EDIT.
// This file was generated by script/write_jsonschema.sh.
// using data from: jsonschema/Args.json

package schema

var argSchemaRaw = []byte(`{
    "$schema": "http://json-schema.org/schema#",
    "title": "job-manager Args schema",
    "type": "object",
    "properties": {
        "type": { "type": "string", "pattern": "^array$" },
        "items": { "type": "array" },
        "minItems": { "type": "number" },
        "maxItems": { "type": "number" }
    },
    "additionalProperties": false,
    "required": ["type"]
}
`)
