// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: api/v1/dequeue.proto

package v1

import (
	v1 "github.com/jeffrom/job-manager/mjob/resource/job/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DequeueJobsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num       int32    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Queues    []string `protobuf:"bytes,2,rep,name=queues,proto3" json:"queues,omitempty"`
	Selectors []string `protobuf:"bytes,3,rep,name=selectors,proto3" json:"selectors,omitempty"`
	Claims    []string `protobuf:"bytes,4,rep,name=claims,proto3" json:"claims,omitempty"`
}

func (x *DequeueJobsRequest) Reset() {
	*x = DequeueJobsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_dequeue_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DequeueJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueJobsRequest) ProtoMessage() {}

func (x *DequeueJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_dequeue_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueJobsRequest.ProtoReflect.Descriptor instead.
func (*DequeueJobsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_dequeue_proto_rawDescGZIP(), []int{0}
}

func (x *DequeueJobsRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *DequeueJobsRequest) GetQueues() []string {
	if x != nil {
		return x.Queues
	}
	return nil
}

func (x *DequeueJobsRequest) GetSelectors() []string {
	if x != nil {
		return x.Selectors
	}
	return nil
}

func (x *DequeueJobsRequest) GetClaims() []string {
	if x != nil {
		return x.Claims
	}
	return nil
}

type DequeueJobsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items  []*v1.Job        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Errors []*ErrorResponse `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *DequeueJobsResponse) Reset() {
	*x = DequeueJobsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_dequeue_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DequeueJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueJobsResponse) ProtoMessage() {}

func (x *DequeueJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_dequeue_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueJobsResponse.ProtoReflect.Descriptor instead.
func (*DequeueJobsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_dequeue_proto_rawDescGZIP(), []int{1}
}

func (x *DequeueJobsResponse) GetItems() []*v1.Job {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *DequeueJobsResponse) GetErrors() []*ErrorResponse {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_api_v1_dequeue_proto protoreflect.FileDescriptor

var file_api_v1_dequeue_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x10,
	0x6a, 0x6f, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x6a, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x74, 0x0a, 0x12, 0x44, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65,
	0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e,
	0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x16, 0x0a,
	0x06, 0x71, 0x75, 0x65, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x71,
	0x75, 0x65, 0x75, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x22, 0x67, 0x0a, 0x13, 0x44,
	0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x2d, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6a, 0x65, 0x66, 0x66, 0x72, 0x6f, 0x6d, 0x2f, 0x6a, 0x6f, 0x62, 0x2d, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x6d, 0x6a, 0x6f, 0x62, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_dequeue_proto_rawDescOnce sync.Once
	file_api_v1_dequeue_proto_rawDescData = file_api_v1_dequeue_proto_rawDesc
)

func file_api_v1_dequeue_proto_rawDescGZIP() []byte {
	file_api_v1_dequeue_proto_rawDescOnce.Do(func() {
		file_api_v1_dequeue_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_dequeue_proto_rawDescData)
	})
	return file_api_v1_dequeue_proto_rawDescData
}

var file_api_v1_dequeue_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_dequeue_proto_goTypes = []interface{}{
	(*DequeueJobsRequest)(nil),  // 0: api.v1.DequeueJobsRequest
	(*DequeueJobsResponse)(nil), // 1: api.v1.DequeueJobsResponse
	(*v1.Job)(nil),              // 2: job.v1.Job
	(*ErrorResponse)(nil),       // 3: api.v1.ErrorResponse
}
var file_api_v1_dequeue_proto_depIdxs = []int32{
	2, // 0: api.v1.DequeueJobsResponse.items:type_name -> job.v1.Job
	3, // 1: api.v1.DequeueJobsResponse.errors:type_name -> api.v1.ErrorResponse
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_v1_dequeue_proto_init() }
func file_api_v1_dequeue_proto_init() {
	if File_api_v1_dequeue_proto != nil {
		return
	}
	file_api_v1_errors_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_v1_dequeue_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DequeueJobsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_dequeue_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DequeueJobsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_dequeue_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_dequeue_proto_goTypes,
		DependencyIndexes: file_api_v1_dequeue_proto_depIdxs,
		MessageInfos:      file_api_v1_dequeue_proto_msgTypes,
	}.Build()
	File_api_v1_dequeue_proto = out.File
	file_api_v1_dequeue_proto_rawDesc = nil
	file_api_v1_dequeue_proto_goTypes = nil
	file_api_v1_dequeue_proto_depIdxs = nil
}
