// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: api/v1/stats.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_stats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_stats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_stats_proto_rawDescGZIP(), []int{0}
}

type StatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Queued               int64 `protobuf:"varint,1,opt,name=queued,proto3" json:"queued,omitempty"`
	Running              int64 `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	Complete             int64 `protobuf:"varint,3,opt,name=complete,proto3" json:"complete,omitempty"`
	Dead                 int64 `protobuf:"varint,4,opt,name=dead,proto3" json:"dead,omitempty"`
	Cancelled            int64 `protobuf:"varint,5,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	Invalid              int64 `protobuf:"varint,6,opt,name=invalid,proto3" json:"invalid,omitempty"`
	Failed               int64 `protobuf:"varint,7,opt,name=failed,proto3" json:"failed,omitempty"`
	LongestUnstartedSecs int64 `protobuf:"varint,8,opt,name=longest_unstarted_secs,json=longestUnstartedSecs,proto3" json:"longest_unstarted_secs,omitempty"`
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_stats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_stats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_stats_proto_rawDescGZIP(), []int{1}
}

func (x *StatsResponse) GetQueued() int64 {
	if x != nil {
		return x.Queued
	}
	return 0
}

func (x *StatsResponse) GetRunning() int64 {
	if x != nil {
		return x.Running
	}
	return 0
}

func (x *StatsResponse) GetComplete() int64 {
	if x != nil {
		return x.Complete
	}
	return 0
}

func (x *StatsResponse) GetDead() int64 {
	if x != nil {
		return x.Dead
	}
	return 0
}

func (x *StatsResponse) GetCancelled() int64 {
	if x != nil {
		return x.Cancelled
	}
	return 0
}

func (x *StatsResponse) GetInvalid() int64 {
	if x != nil {
		return x.Invalid
	}
	return 0
}

func (x *StatsResponse) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *StatsResponse) GetLongestUnstartedSecs() int64 {
	if x != nil {
		return x.LongestUnstartedSecs
	}
	return 0
}

var File_api_v1_stats_proto protoreflect.FileDescriptor

var file_api_v1_stats_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x22, 0x0e, 0x0a, 0x0c,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xf7, 0x01, 0x0a,
	0x0d, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x65, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x64, 0x65, 0x61, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x69, 0x6c,
	0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64,
	0x12, 0x34, 0x0a, 0x16, 0x6c, 0x6f, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x5f, 0x75, 0x6e, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x63, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x14, 0x6c, 0x6f, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x55, 0x6e, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x65, 0x64, 0x53, 0x65, 0x63, 0x73, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x65, 0x66, 0x66, 0x72, 0x6f, 0x6d, 0x2f, 0x6a, 0x6f, 0x62,
	0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x6d, 0x6a, 0x6f, 0x62, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_stats_proto_rawDescOnce sync.Once
	file_api_v1_stats_proto_rawDescData = file_api_v1_stats_proto_rawDesc
)

func file_api_v1_stats_proto_rawDescGZIP() []byte {
	file_api_v1_stats_proto_rawDescOnce.Do(func() {
		file_api_v1_stats_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_stats_proto_rawDescData)
	})
	return file_api_v1_stats_proto_rawDescData
}

var file_api_v1_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_stats_proto_goTypes = []interface{}{
	(*StatsRequest)(nil),  // 0: api.v1.StatsRequest
	(*StatsResponse)(nil), // 1: api.v1.StatsResponse
}
var file_api_v1_stats_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_stats_proto_init() }
func file_api_v1_stats_proto_init() {
	if File_api_v1_stats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_stats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_stats_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_stats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_stats_proto_goTypes,
		DependencyIndexes: file_api_v1_stats_proto_depIdxs,
		MessageInfos:      file_api_v1_stats_proto_msgTypes,
	}.Build()
	File_api_v1_stats_proto = out.File
	file_api_v1_stats_proto_rawDesc = nil
	file_api_v1_stats_proto_goTypes = nil
	file_api_v1_stats_proto_depIdxs = nil
}
