// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: api/v1/errors.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NotFoundErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource string `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *NotFoundErrorResponse) Reset() {
	*x = NotFoundErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_errors_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotFoundErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotFoundErrorResponse) ProtoMessage() {}

func (x *NotFoundErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_errors_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotFoundErrorResponse.ProtoReflect.Descriptor instead.
func (*NotFoundErrorResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_errors_proto_rawDescGZIP(), []int{0}
}

func (x *NotFoundErrorResponse) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type ValidationErrorArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path  string         `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Msg   string         `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Value *_struct.Value `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ValidationErrorArg) Reset() {
	*x = ValidationErrorArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_errors_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidationErrorArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationErrorArg) ProtoMessage() {}

func (x *ValidationErrorArg) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_errors_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationErrorArg.ProtoReflect.Descriptor instead.
func (*ValidationErrorArg) Descriptor() ([]byte, []int) {
	return file_api_v1_errors_proto_rawDescGZIP(), []int{1}
}

func (x *ValidationErrorArg) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ValidationErrorArg) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ValidationErrorArg) GetValue() *_struct.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type ValidationErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errs []*ValidationErrorArg `protobuf:"bytes,1,rep,name=errs,proto3" json:"errs,omitempty"`
}

func (x *ValidationErrorResponse) Reset() {
	*x = ValidationErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_errors_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidationErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationErrorResponse) ProtoMessage() {}

func (x *ValidationErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_errors_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationErrorResponse.ProtoReflect.Descriptor instead.
func (*ValidationErrorResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_errors_proto_rawDescGZIP(), []int{2}
}

func (x *ValidationErrorResponse) GetErrs() []*ValidationErrorArg {
	if x != nil {
		return x.Errs
	}
	return nil
}

var File_api_v1_errors_proto protoreflect.FileDescriptor

var file_api_v1_errors_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a, 0x15, 0x4e,
	0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x22, 0x68, 0x0a, 0x12, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x41, 0x72, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2c, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x49, 0x0a, 0x17, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x65, 0x72, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x41, 0x72, 0x67, 0x52,
	0x04, 0x65, 0x72, 0x72, 0x73, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x65, 0x66, 0x66, 0x72, 0x6f, 0x6d, 0x2f, 0x6a, 0x6f, 0x62, 0x2d,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_errors_proto_rawDescOnce sync.Once
	file_api_v1_errors_proto_rawDescData = file_api_v1_errors_proto_rawDesc
)

func file_api_v1_errors_proto_rawDescGZIP() []byte {
	file_api_v1_errors_proto_rawDescOnce.Do(func() {
		file_api_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_errors_proto_rawDescData)
	})
	return file_api_v1_errors_proto_rawDescData
}

var file_api_v1_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_v1_errors_proto_goTypes = []interface{}{
	(*NotFoundErrorResponse)(nil),   // 0: api.v1.NotFoundErrorResponse
	(*ValidationErrorArg)(nil),      // 1: api.v1.ValidationErrorArg
	(*ValidationErrorResponse)(nil), // 2: api.v1.ValidationErrorResponse
	(*_struct.Value)(nil),           // 3: google.protobuf.Value
}
var file_api_v1_errors_proto_depIdxs = []int32{
	3, // 0: api.v1.ValidationErrorArg.value:type_name -> google.protobuf.Value
	1, // 1: api.v1.ValidationErrorResponse.errs:type_name -> api.v1.ValidationErrorArg
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_v1_errors_proto_init() }
func file_api_v1_errors_proto_init() {
	if File_api_v1_errors_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_errors_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotFoundErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_errors_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidationErrorArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_errors_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidationErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_errors_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_errors_proto_goTypes,
		DependencyIndexes: file_api_v1_errors_proto_depIdxs,
		MessageInfos:      file_api_v1_errors_proto_msgTypes,
	}.Build()
	File_api_v1_errors_proto = out.File
	file_api_v1_errors_proto_rawDesc = nil
	file_api_v1_errors_proto_goTypes = nil
	file_api_v1_errors_proto_depIdxs = nil
}
