// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: job/v1/backoff.proto

package v1

import (
	duration "github.com/golang/protobuf/ptypes/duration"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Backoff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Initial *duration.Duration `protobuf:"bytes,1,opt,name=initial,proto3" json:"initial,omitempty"`
	Max     *duration.Duration `protobuf:"bytes,2,opt,name=max,proto3" json:"max,omitempty"`
	Factor  float32            `protobuf:"fixed32,3,opt,name=factor,proto3" json:"factor,omitempty"`
}

func (x *Backoff) Reset() {
	*x = Backoff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_v1_backoff_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Backoff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backoff) ProtoMessage() {}

func (x *Backoff) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_backoff_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backoff.ProtoReflect.Descriptor instead.
func (*Backoff) Descriptor() ([]byte, []int) {
	return file_job_v1_backoff_proto_rawDescGZIP(), []int{0}
}

func (x *Backoff) GetInitial() *duration.Duration {
	if x != nil {
		return x.Initial
	}
	return nil
}

func (x *Backoff) GetMax() *duration.Duration {
	if x != nil {
		return x.Max
	}
	return nil
}

func (x *Backoff) GetFactor() float32 {
	if x != nil {
		return x.Factor
	}
	return 0
}

var File_job_v1_backoff_proto protoreflect.FileDescriptor

var file_job_v1_backoff_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6a, 0x6f, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x6f, 0x66, 0x66,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6a, 0x6f, 0x62, 0x2e, 0x76, 0x31, 0x1a, 0x1e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83,
	0x01, 0x0a, 0x07, 0x42, 0x61, 0x63, 0x6b, 0x6f, 0x66, 0x66, 0x12, 0x33, 0x0a, 0x07, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x12,
	0x2b, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x66, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6a, 0x65, 0x66, 0x66, 0x72, 0x6f, 0x6d, 0x2f, 0x6a, 0x6f, 0x62, 0x2d, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x6d, 0x6a, 0x6f, 0x62, 0x2f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x2f, 0x6a, 0x6f, 0x62, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_job_v1_backoff_proto_rawDescOnce sync.Once
	file_job_v1_backoff_proto_rawDescData = file_job_v1_backoff_proto_rawDesc
)

func file_job_v1_backoff_proto_rawDescGZIP() []byte {
	file_job_v1_backoff_proto_rawDescOnce.Do(func() {
		file_job_v1_backoff_proto_rawDescData = protoimpl.X.CompressGZIP(file_job_v1_backoff_proto_rawDescData)
	})
	return file_job_v1_backoff_proto_rawDescData
}

var file_job_v1_backoff_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_job_v1_backoff_proto_goTypes = []interface{}{
	(*Backoff)(nil),           // 0: job.v1.Backoff
	(*duration.Duration)(nil), // 1: google.protobuf.Duration
}
var file_job_v1_backoff_proto_depIdxs = []int32{
	1, // 0: job.v1.Backoff.initial:type_name -> google.protobuf.Duration
	1, // 1: job.v1.Backoff.max:type_name -> google.protobuf.Duration
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_job_v1_backoff_proto_init() }
func file_job_v1_backoff_proto_init() {
	if File_job_v1_backoff_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_job_v1_backoff_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Backoff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_job_v1_backoff_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_job_v1_backoff_proto_goTypes,
		DependencyIndexes: file_job_v1_backoff_proto_depIdxs,
		MessageInfos:      file_job_v1_backoff_proto_msgTypes,
	}.Build()
	File_job_v1_backoff_proto = out.File
	file_job_v1_backoff_proto_rawDesc = nil
	file_job_v1_backoff_proto_goTypes = nil
	file_job_v1_backoff_proto_depIdxs = nil
}
